id: jbossdemocentral-bpms-ecm
title: Demo is a telco story of customer working with process to activate her mobile service by downloading a service contract document, signing it (update), and uploading the results back into the process.
github_repo_url: https://github.com/jbossdemocentral/bpms-ecm-demo
technologies:
  - JBoss EAP
  - JBoss BPM Suite
summary: Project to automate the installation of this product with ECM (document integration with BPM) demo project. Demo is a telco story of customer working with process to activate her mobile service by downloading a service contract document, signing it (update), and uploading the results back into the process. There are two options available to you for using this demo; local and containerized. 
level: Beginner
product: bpmsuite
author: Maciej Swiderski, Andrew Block, Eric D. Schabell
